### ISSUE TITLE
Deleting a file from repos does not trigger a proper cleanup

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/outside-collaborators#17]
When a YAML file gets removed from [repos][1], the subsequent action won't be able to perform any cleanup of the repository corresponding to that particular file as the file is simply missing and the ruby script won't find it out.

The current workaround is to clean up the repository manually.

[1]: ../blob/master/repos

**Comment by pattacini** [comment]
Need to test whether the following example with an empty list may do the job:
```yml
repo_name_1:
```

**Comment by pattacini** [comment]
@S-Dafarra, for fixing this bug I've just added you to `cad-libraries` w/ "`read`" permission.
I'll be now proceeding with my test.

**Comment by pattacini** [comment]
Got the following error:
```sh
./outside-collaborators-handler.rb:204:in `block in <main>': undefined method `each' for nil:NilClass (NoMethodError)
	from ./outside-collaborators-handler.rb:189:in `each'
	from ./outside-collaborators-handler.rb:189:in `<main>'
```

**Comment by pattacini** [comment]
The above bug has been sorted out and the approach resorting to empty repo's entry demonstrated to work just fine ✔
